server:
  port: 8081

spring:
  application:
    name: accounts

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: myapp
            client-secret: "ItA5iKPMj3jRqroIy8pVpdjbDEkDpKar"
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/myapp-realm
            jwk-set-uri: http://localhost:8080/realms/myapp-realm/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG
    com.nimbusds.jwt: DEBUG
